name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Восстановить Keys.cs из секрета
      run: |
        mkdir -p CinemaTelegramBot/App
        echo "${{ secrets.KEYS_CS }}" > CinemaTelegramBot/App/Keys.cs

    - name: Посмотреть содержимое Keys.cs
      run: cat CinemaTelegramBot/App/Keys.cs
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
